### ISSUE TITLE
Error when requesting Spotify API

### ISSUE THREAD

**Issue by FunctionalHacker** [dbeley/ypc#20]
Okay another issue. I set up my application on developer.spotify.com and input the id and secret to ~/.config/ypc/config.ini and here is the debug output:

```
~
❯ ypc "https://open.spotify.com/playlist/7uMaCaduN39Y6xk3dMkt7G?si=W-YGzrRKQYCOuhHDbicPHA" --debug
DEBUG :: Export folder : ypc_exports.
DEBUG :: urls : ['https://open.spotify.com/playlist/7uMaCaduN39Y6xk3dMkt7G?si=W-YGzrRKQYCOuhHDbicPHA'].
DEBUG :: Function get_spotify_playlists.
INFO :: Processing spotify playlist https://open.spotify.com/playlist/7uMaCaduN39Y6xk3dMkt7G?si=W-YGzrRKQYCOuhHDbicPHA
DEBUG :: Starting new HTTPS connection (1): accounts.spotify.com:443
DEBUG :: https://accounts.spotify.com:443 "POST /api/token HTTP/1.1" 200 None
DEBUG :: Starting new HTTPS connection (1): api.spotify.com:443
DEBUG :: https://api.spotify.com:443 "GET /v1/users/spotify/playlists/7uMaCaduN39Y6xk3dMkt7G?si=W-YGzrRKQYCOuhHDbicPHA/tracks&limit=100&offset=0 HTTP/1.1" 200 None
ERROR :: Error when requesting Spotify API. Be sure that your config.ini file is correct. Error : 'items'
```

**Comment by dbeley** [comment]
Hello ! Yes there was a bug where I assumed every spotify playlists were owned by spotify, in fact I've never tested any user-made playlist. It should be working now (if it doesn't work, "clean" the url by deleting everyting after the quotation mark (including the quotation mark)).

You might face one last problem, the youtube rate-limit error. I use webscraping to search youtube urls for each songs, and unfortunately youtube has pretty aggressive rate-limit protection. The solution to that would be to use the youtube api (I will try to do some research on it, maybe this weekend).

**Comment by FunctionalHacker** [comment]
Okay don't sweat it too much :+1:

I'm not at my PC now but I can test it later. If you want me to test anything else, let me know. I also have some coding experience, just not much with python so I can try to help with something.

**Comment by dbeley** [comment]
Hello I've made some progress on this, in fact youtube-dl allows searching for videos and taking the first result so there's no need to use the weird webscraping anymore. It also means there are no more rate-limit protection.
